--cookies-from-browser vivaldi

-o "[%(uploader)s] %(title)s.%(ext)s"

# download 3 fragments at a time
-N 3

--embed-metadata
# --embed-thumbnail

--sponsorblock-remove "selfpromo,sponsor"

# replace weird dashes
--replace-in-metadata "title,uploader" "–" "-"