---@module 'hl'

-- Generated by nwg-displays on 2026-02-25 at 21:54:58. Do not edit manually.

hl.monitor({
    output   = "desc:Sharp Corporation 0x1517",
    mode     = "3840x2400@59.99",
    position = "2142x1440",
    scale    = 2.0,
})

hl.monitor({
    output   = "desc:BBY INSIGNIA-TV 0x00000001",
    mode     = "3840x2160@60.0",
    position = "1920x0",
    scale    = 1.5,
})
