set -g mouse on
bind -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down   

# makes different windows part of different groups, meaning killing one window doesn't kill the whole session.
set-option -g default-command 'systemd-run --user --scope bash'